version: 0.0
os: linux
files:
 - source: /
   destination: /home/ubuntu/wisest-backend/
hooks:
  AfterInstall:
   - location: start_server
     timeout: 300
     runas: ubuntu
  ApplicationStart:
   - location: start_server
     timeout: 300
     runas: root
